### PR TITLE
Fix teardown

### PR DESCRIPTION
**Pull request by hughperkins**
Fixes issue https://github.com/clMathLibraries/clBLAS/issues/159

What is the issue?
- teardown doesnt re-initialize the autogemm kernels to null

What is the effect of the issue?
- following sequence causes segfault:
  - clblassetup
  - gemm
   - clblasteardown
   - clblassetup
   - gemm

How does the fix work?
- AutoGemm now adds a new method to set the autogemm kernels to null
- init.c contains a call to this new method

(Note that this also incorporates pull request for 'array initialize must be an initializer list', otherwise gemm doesnt get very far on my machine :-P )

### CODE REVIEW

**Comment by hughperkins** [comment]
Note: example output for the same sourecode as in https://github.com/clMathLibraries/clBLAS/issues/159:

```
$ LD_LIBRARY_PATH=../build/library/ ./test
i=0
got platformids
got deviceids
created context
created commandqueue
setup blas ok
calling sgemm....

clblasSgemmEx result:
11 12 13 
21 35720 36680 
31 50720 52080 
41 65720 67480 
finished ok :-)
i=1
got platformids
got deviceids
created context
created commandqueue
setup blas ok
calling sgemm....

clblasSgemmEx result:
11 12 13 
21 35720 36680 
31 50720 52080 
41 65720 67480 
finished ok :-)
i=2
got platformids
got deviceids
created context
created commandqueue
setup blas ok
calling sgemm....

clblasSgemmEx result:
11 12 13 
21 35720 36680 
31 50720 52080 
41 65720 67480 
finished ok :-)
```

**Comment by hughperkins** [comment]
(Updated commit to call `clReleaseKernel` on the kernel first)

**Comment by hughperkins** [comment]
(I think this new commit has addressed issue https://github.com/clMathLibraries/clBLAS/issues/166  , at least in combination with the fix identified in https://github.com/clMathLibraries/clBLAS/issues/167 )

**Comment by guacamoleo** [comment]
Hugh's concern and fix are both legit. I checked out his commit and validated that it passes the gemm tests.

**Comment by hughperkins** [comment]
Thanks!

**Comment by hughperkins** [comment]
Hi.  Just realized that this fails to build the first time, since include/AutoGemmIncludes/AutoGemmClKernels.cpp isnt present. And init.c is compiled before the generation step.

**Pull request merged**
