### PR TITLE
For discussion: fix memory leak with xgemm

### PR DESCRIPTION
**Pull request by hughperkins**
This addresses a memory leak in xgemm, which causes the cl context to not be released during teardown, consuming ~50-70MB per setup/release cycle, https://github.com/clMathLibraries/clBLAS/issues/247

I've labelled this as 'for discussion', since it's not thread safe.  It is however suitable for my own use, but it should hvae some mutexes or similar to work for multi-threading scenarios.

---

This change is [Reviewable](https://reviewable.io/reviews/clmathlibraries/clblas/250)

### CODE REVIEW

**Comment by pavanky** [comment]
I got the mutex stuff to work but was having issues with the tuner and ktest not compiling.. Looks like all I had to do was put it inside the ifdef block..

I will rebase my work based on yours and send in a new PR (you wont lose your commit)

**Comment by hughperkins** [comment]
Cool. Sounds good :-)

**Comment by kknox** [comment]
Any update on this?

**Comment by pavanky** [comment]
@kknox got carried away with other stuff on my plate. I will see if I can get something done this week.

**Comment by kknox** [comment]
Closing for inactivity

**Pull request closed without merging**
